### ISSUE TITLE
Transformer group reduces number of pipelines too much

### ISSUE THREAD

**Issue by jakubklimek** [linkedpipes/discovery#13]
When transformer groups are present, the number of discovered pipelines is reduced too much.

https://discovery.linkedpipes.com/resource/discovery/timeline-test-1/config and https://discovery.linkedpipes.com/resource/discovery/timeline-test-1g/config are the same discovery configurations, except 1g has a transformer group with one member. The results should be identical, however, the discovery without a group finds 29 pipelines, the discovery with the group finds 16 pipelines.

**Comment by jirihelmich** [comment]
Iteration 1 finds 14 pipeline fragments, all ending with the transformer. As per your request, all those pipelines are groupped and replaced by one pipeline, containing all matching transformers from that group (the same one).

So if the number of transformers from group that matched is 1, I should not follow this logic?

**Comment by jakubklimek** [comment]
I don't think that is the problem. The problem is this:
Without groups, I find a pipeline which contains the transformer:
![image](https://user-images.githubusercontent.com/718827/36657890-a585647a-1ace-11e8-8abe-a0e1ffe7b32d.png)
With groups, this pipeline is not found and IMHO should be:
![image](https://user-images.githubusercontent.com/718827/36657901-b302d0ba-1ace-11e8-8454-814ef179eed1.png)
