### ISSUE TITLE
It takes 30 minutes to get the results of a discovery with 999 pipelines

### ISSUE THREAD

**Issue by jakubklimek** [linkedpipes/discovery#17]
The discovery runs for 1 minute. But to get the 50 kb zip file with the results, I have to wait for 30 minutes.

https://discovery.linkedpipes.com/resource/experiment/all-and-generated/config

**Comment by jirihelmich** [comment]
Now takes around 9 seconds on my notebook. I just hope it produces the same data, could you compare? Shouldn't have lost anything.
